spring:
  application:
    name: Review API  data:    jpa:      repositories:        bootstrap-mode: deferred
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    hibernate:      ddl-auto: none  devtools:    restart:      enabled: true
    livereload:      enabled: true  jackson:    serialization:      indent-output: true
  datasource:    url: jdbc:mysql://localhost:3306/zirius
    username: root
    password: vigguraj55
    driver-class-name: com.mysql.cj.jdbc.Driver
server:  port: 8081 
    